### ISSUE TITLE
Problem with retropad's default input mapping in MAME

### ISSUE THREAD

**Issue by Reznnate** [libretro/mame#15]
Most retropad buttons are no longer bound (by default)

Select, Start, Left-analog stick, a,b,x,y, lb, rb are currently bound (for Street Fighter 2!)

Previously L2 was mapped to OSD menu (TAB), R2 was mapped to framerate
Previously L3/R3 were mapped to reset and service mode (needed to start many arcade games)
The dpad is no longer mapped, but should follow Left analog
Right analog stick should be mapped for dual-stick shooters (Robotron, Smash TV, etc.)

**Comment by r-type** [comment]
@Reznnate , I will still try to take the time to reply , as you open an github issue ,to explain why for now I have not renewed the default key assignment as before.
in previous versions , i got a lot of complain from users about the default assignment , which cannot be change by user and which was hard coded .
in fact we did an fake keyboard device and hard-code L2/R2/L3 and PAD UP/DN/LFT/RGT.

I didn't want to reproduce it with last mame core , so i remove the "hard coded" keyboard device.
all the previous "hardcoded" input are bind to a 'mame joystick button' 

Now you can assign a button to what you want , by using mame OSD menu .
but I m agree on android it's a problem to hit an tab key.
I usually use the keyboard overlay to do it , but recently i found a bug that prevent me to use it ,
because when I leave keyboard overlay ,the joystick overlay is not enabled . then you cant control the emulator after.

So , in short , I will look at a way to enable TAB key on android when I'll have time.

**Comment by r-type** [comment]
i added 2 combo that can be useful 
Select + Joy_but3 => UI Menu
Select + Start => CANCEL

**Comment by Reznnate** [comment]
@r-type , I follow... If you can re-assign inputs as normal with the OSD menu, this makes sense to me. 
On Android, my attempt to connect a keyboard (with various hotkey changes) and reach the OSD menu failed so I'll wait for the latest build to confirm this works.

On a related note, how are the default MAME input bindings created and defined?   For the Android core in particular (and other platforms with default controllers), mapping the defaults (I mentioned above) to the Retroarch retropad would be very nice so you wouldn't have to remap them each time you updated the core.

**Comment by Reznnate** [comment]
@r-type  Spent some time testing tonight and ran into a few issues.    With updated mame core, I can raise the OSD menu but I wasn't able to properly config for a dual-stick shooter (i.e. Robotron).   

1) RA lacks ext-storage permission -- If I launch mame rom directly with Retroarch, the mame file paths are derived from rom path (and not writeable without ext-storage permission).     In this case, nvram state doesn't change and I couldn't bypass Robotron's initial factory reset state.

2)  The 'reset' core-option isn't working.  

So I shifted my testing to a Hyperspin (launcher) setup.   In this case, the Retroarch launcher intent loses path info so it uses it's internal /data/data folder for nvram files.    I can play Robotron.

3) The OSD config files aren't being saved or loaded (although options were toggled in core-options).   I needed to modify them for each test.

4) After setting the controls manually in the OSD menu, the up/dn/lt/rt controls for right stick are bound to right stick diagonals instead.    I was unable to fire in cardinal directions.

**Comment by andres-asm** [comment]
The ext storage permission was solved in a commit by some guy but had to be
rolled back. I'll check it out.

**Comment by Reznnate** [comment]
In the lastest MAME core (v181 on Android), the default retropad mapping for MAME controls changed again.   

Select + Joy_but3 => does not launch the OSD menu
Select + Start => launches mame's default gui for launching roms

**Comment by r-type** [comment]
Strange as noting change since.
I use updater to get the last mame and select+x (tab) bring the OSD menu.
and select+start (esc) close current content and bring to mame default GUI as expected.
I'm not sure why it's not working for you.

**Comment by Reznnate** [comment]
@r-type   It is indeed working with Select + Joy_but3 (Y button on my controller).   I couldn't recall how to launch OSD button and came back to this report to find out.    My mistake is that I mis-interpreted Joy_But3 for Joystick-button-press.   Had I looked in Information->Core information, Retropad Select+X is listed.  Sorry!

I'll open separate issue for mapping of right-analog-stick.  After changing setting in OSD menu, it behaves like a qbert controller (diagonals only).

Thank you for quick response, closing bug.

**Comment by sm-Fifteen** [comment]
Select+Start does not seem easily remappable, which is problematic since that's one of the listed combinations to bring up the retroarch UI on controllers where the HOME button is absent or already used. Also, since launching ROMs is supposed to be the frontend's responsibility, what's the point of mapping CANCEL on anything?
