### ISSUE TITLE
Freezing with "Initializing" screen latest version from git.

### ISSUE THREAD

**Issue by breisig** [libretro/mame#158]
I have compiled the latest version from git today on the latest retropie on a rp4b. It seems when running roms that work with other mame versions(mame2016), it also works with this mame. But, if you run any rom (example: galaga) that doesn't work with mame2016 and exits successful, it just shows the word "Initializing" in a white boxed window and freezes. I cant quit or anything.

**Comment by HoJo215** [comment]
You need the romset that goes with the mame build.. in this case it would be 0.220

**Comment by breisig** [comment]
Thanks, The big problem is that it doesn't automatically exit but instead the program just freezes. I can't hit any key to do anything.

**Comment by tcamargo** [comment]
Know issue. Check your rom against a good 0.222 romset.

**Comment by c0d3h4x0r** [comment]
Yes, it's a known issue -- and it still needs to be fixed.  Hanging is not an acceptable or intuitive user experience, despite there being a workaround.

**Comment by jlopezvil** [comment]
What about fixing this issue?. I can report also freezing happens when you load a rom that is not complete .. I have solved using linux command to terminate process lr-mame, but it not a clean solution, is a command line solution not for users ....

Greetings and all acknowlege for your great work with this port ...    

Games runs fantastic ... when not freeze on start ...   :)

**Comment by breisig** [comment]
This issue should seriously get prioritized to get fixed.

**Comment by barbudreadmon** [comment]
The hbmame core got the same issue, which seems legit since its libretro implementation seems to have been copied from this core.

**Comment by vus7294** [comment]
Taito G-NET is Now Unplayable Because Same Cause at Crash at Initializing after 0.222

**Comment by breisig** [comment]
I guess no one wants to debug this.

**Comment by tcamargo** [comment]
> Taito G-NET is Now Unplayable Because Same Cause at Crash at Initializing after 0.222

Make sure you get a compatible romset and games will run.

**Comment by jason-oliveira** [comment]
@tcmargo is there a way you could elaborate on what the roadblock is for providing a fix on this issue? On the surface, it looks like the failure state needs to be acted upon so the core can die gracefully.

**Comment by markwkidd** [comment]
Ideally the core would display a notification that the romset is incorrect, run for another five seconds or so, then exit gracefully.

The first step is to identify where in the MAME code it is polling the keyboard and waiting for input. Any chance someone already knows where that code is? 😁

**Comment by tcamargo** [comment]
We use the OSD interface from mame to implement one OSD for libretro. So, check https://github.com/libretro/mame/blob/master/src/osd/modules/input/input_retro.cpp.

Sometime core freezes with a blank screen, sometimes with a "Initializing" message. You usually can check what is missing on stdout/log. Maybe a good starting point is where mame is initialize: https://github.com/libretro/mame/blob/015dc4f5bd8a1cc347e00e08ec575a4b0e60016d/src/osd/libretro/libretro-internal/retro_init.cpp#L767

**Comment by mahoneyt944** [comment]
Can't we just bail anytime a rom is missing or incorrect during rom loading?

**Comment by markwkidd** [comment]
> Can't we just bail anytime a rom is missing or incorrect during rom loading?

Seems like the right approach. An error message for the user would be nice, but that could be phase 2. This is hopefully just a couple of lines to change...... Knock on wood...

**Comment by mahoneyt944** [comment]
@markwkidd I think we could just call to close content here. Might even be able to change that to a libretro log for the fatal error.

https://github.com/libretro/mame/blob/015dc4f5bd8a1cc347e00e08ec575a4b0e60016d/src/emu/romload.cpp#L572-L591

**Comment by tcamargo** [comment]
No changes to mame source please. Better see if you can override osd_printf_error/warning and add an error to exception.

**Comment by markwkidd** [comment]
It seems like MAME's function is to poll keyboard input or whatever here. No matter how we describe it, we want to disregard MAME's intention.

It seems better to change the behavior in a way that is straightforward and easy to understand.

**Comment by markwkidd** [comment]
Could we propose to upstream that this behavior be optional, and there is a way for OSDs to request that it not do this?

**Comment by mahoneyt944** [comment]
Hmm well how to change code without changing it. A crazy idea might be scan the log for the fatal error and launch our own?

**Comment by markwkidd** [comment]
Sorry for multiple posts in a row, but I have only looked at the modern mame codebase a few times over the last few years.

I probably misunderstood the comment about overriding osd_printf_error -- I now think what we're talking about is that this mame core maybe doesn't implement libretro logging yet. So the advice is to implement logging in order to better diagnose the error?

Makes sense I guess but my dream of a couple lines of code is flying away.

Logging seems like a bare minimum, maybe implementing that is the critical project for this core.

**Comment by tcamargo** [comment]
It implements logging but I didn’t check we provide something meaningful in our osd_printf implementation. Second step is to see why that throw is hanging retroarch.

**Comment by mahoneyt944** [comment]
I'll relay this here as I posted this on discord already.

It seems our goal here is to figure out how to monitor the core's pulse and create an exit plan for when it's dead while not disturbing the mame source. As a last ditch effort, this maybe a compromise we have to take so that the core is stable and yields a positive user experience.

But for now, I think we could brain storm on some clever ways to monitor the core. I think one approach would be to monitor the frame count. On my tests with loading invalid roms, each one displays a frame count of "n/a". We may be able to track the frame count and compare the value to see if it's valid or not. If it isn't, exit.
![Screenshot_20210826-192815](https://user-images.githubusercontent.com/49591133/131067408-25688dd8-fd1e-4f83-a9ed-7ae751063de6.png)

The first step would be to see what, if anything, is still firing when this lockup occurs. We can add some logging into any libretro side functions then deliberately load roms known to crash as a control and see if we get anything.

I believe retroarch is hanging because the mame code is hanging and not allowing it to execute it's next frame. Inputs and video aren't responsive.

**Comment by tcamargo** [comment]
Please test when builds are ready.

https://git.libretro.com/libretro/mame/-/pipelines/49446

**Comment by breisig** [comment]
Why was this closed? It's not fixed it

**Comment by tcamargo** [comment]
> Why was this closed? It's not fixed it

It is. Download a test core from https://git.libretro.com/libretro/mame/-/pipelines/49446.
