### ISSUE TITLE
MAME support for Retropad's right analog stick

### ISSUE THREAD

**Issue by Reznnate** [libretro/mame#17]
When using OSD menu to assign retropad right-analog-stick controls for games like Robotron, SmashTV, etc., the right stick only fires in diagonal directions.

**Comment by Reznnate** [comment]
This problem is specific to this mame core.   IN the mame2014 core, Using the OSD menu, I can re-assign the right analog stick and the right stick fires in the expected, cardinal directions.    My testing is on Android.

**Comment by Dunard** [comment]
I having that issue too. But on the 0.188. Two different controllers tested. Works fine on the MAME64 though. Seem like the DEV haven't got around with a fix yet.

**Comment by tcamargo** [comment]
Could you please confirm this problem on a newer build? Thx! If it is confirmed, I will reopen this issue.

**Comment by roslof** [comment]
Good morning @tcamargo 

This is a request to reopen this issue. This is a verified bug on all lr-mame versions up to 0.224, that when properly configured, R-Stick controls only register in the diagonal directions (Black Widow, Cloak & Dagger, Krull, Robotron 2084, Sheriff, Smash TV, Space Dungeon, etc.) I confirmed this is also an issue with lr-mame2016.

**TEST 1:** When binding the R-Stick to all four directions (Up, Down Left and Right) the R-Stick only registers diagonal data. (I believe if you bind exactly one direction, that direction will appear correct, but it breaks when paired with an adjacent input, then the diagonal issue occurs).

**TEST 2:** When binding the R-Stick **AND four buttons** to all four directions (Up, Down Left and Right) the R-Stick only registers diagonal data, but the buttons work correctly (individual buttons like the DualShock Triangle (Up), X (Down), Square (Left) and Circle (Right) will independently register the correct direction and when combined (corded) will also, correctly shoot diagonally. This confirms the issue is solely with the R-Stick control.

It is fairly simple to test. The bug has been in both lr-mame and lr-2016 core since the issue was reported over 3 years ago. All attempts to find a work-around have been futile. I test regularly on Raspberry Pi 3B+ and Raspberry Pi 4B. Various controllers have been used, but I primarily work with the Sony Dual Shock 4.

FWIW: I also regularly test lr-mame2003, lr-mame2003plus, lr-mame2010, lr-mame2015 and none exhibit this consistent behavior. I maintain a [recommended arcade emulator list](https://docs.google.com/spreadsheets/d/1Rq4shU1RUSdcc7cTVWeORMD-mcO6BwXwQ7TGw8f5_zw/edit#gid=0) and noted that vector games are especially good with lr-mame, but I recommend other emulators for games like Black Widow due to this issue.

Hope this is helpful.
