### ISSUE TITLE
Resolution / stretch issue - feedback

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/mame#2]
New issue to give some feedback. That's on win7 x64.

Core without libco: The stretching problem is still here [(old vertical strip rendering)](https://github.com/twinaphex/mame-old/issues/3), x68000 is slow and the image is glitched (distorted in diagonal).
Then I can't launch x68000 games again after my first test: it's crashing at AV change.
(no core-option cfg, no nvram, nothing... strange)

The ui.bdf trick seems to work.

Core with libco: Always crash on mame GUI message "loading Machine" while booting.
I tried with altered rendering too but it's the same.
[Backtrace gave me this.](http://pastebin.com/dCCd2tiD)

**Comment by r-type** [comment]
The crash is due to a bad issue with ui.bdf not shure why but it crash sometime when create the cache file ui.bdc. can you test using the create cache file  here: http://dl.free.fr/fdog8Cvpo
(to put in same place than ui.bdf)

Libco  crash is because mainly an exception crash , you surely build with an SEH toolchain ,and it crash with libco.
to know if your Tc is SEH just compil
g++ -S fic.c -o output.s

```
struct S { ~S(); };
void bar();
void foo() {
  S s;
  bar();
}
```

and if you have     

```
.def    __gxx_personality_seh0; .scl    2;  .type   32; .endef
```

then you have a SEH tc .
So use a SJLJ Toolchain for using with LIBCO
or tweak libco.c to force use fibers instead amd64.

Btw it's not a very mature core ,and very WIP, better using the 174 with ui.bdf trick.

**Comment by Tatsuya79** [comment]
I had the ui.bdc as I could launch a game that wasn't x68000.
I tried with yours but that's the same: working for standard game, crashing for x68000.

For Libco version that's probably as you say as I'm using the MSYS2 tutorial without much understanding of all this stuff.
Guess I'll wait for a while.
Just ask here if you need any testing on windows later.

**Comment by r-type** [comment]
I don't know for your x68k  crash problem , strange.
but anyway i found what cause the speed issue after doing a perf report  .
seem some lua process take to much cpu.

![retroarch](https://cloud.githubusercontent.com/assets/3614417/20284616/2b9e51de-aabe-11e6-8f44-b4d24fe5cc2c.png)
commits related to lua have been done since my initial 0.179 port like
https://github.com/mamedev/mame/commit/2de04414ed0fdff027eb99c83faca2074a944bc6

if i comment in emulator_info::frame_hook() from src/frontend/mame/mame.cpp  
this line

```
    //return mame_machine_manager::instance()->lua()->frame_hook();
```

Speed is normal.
