### ISSUE TITLE
Restore 0.219 branch for Tiger and Konami LCD titles

### ISSUE THREAD

**Issue by slaminger** [libretro/mame#270]
The last version of the MAME core I have been able to get Tiger and Konami LCD  games to work on, for RPI4, Odroid and Anbernic devices is this version of the core. Support does not appear to be present in later versions, please add the 0.219 branch back to the repo so it can be compiled by users wishing to play the LCD games.

**Comment by tcamargo** [comment]
Checkout mame0219.

https://github.com/libretro/mame/tree/mame0219

**Comment by inactive123** [comment]
If need be we could add MAME 0.219 to the buildbot - we first have to give it a dated filename though (2019/2020?).

Unless of course it's something that can be fixed in the latest mainline. Out of interest, why would this no longer work in the latest versions? Is this something we can potentially look at getting to work in the latest mainline or did they break it or remove it from future MAME versions and is that the reason why 0.219 is the last one where it still worked?

**Comment by tcamargo** [comment]
Probably because buildbot is only building the arcade profile for some platforms. Don’t remember when we did that.

**Comment by inactive123** [comment]
Oh, I think we probably only did that for Android because otherwise the core was too big to link for Android's linker.
