### ISSUE TITLE
libreto mame 0.244 not compiling

### ISSUE THREAD

**Issue by jlopezvil** [libretro/mame#310]
The new release is not compiling. There is some error in linux compile. 
No error messages but only compile fails.

**Comment by shad00m** [comment]
```cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: error: use -Winvalid-pch for more information
cc1plus: fatal error: ../../../../libretro/obj/libretro/emu.h: No such file or directory
compilation terminated.
make[3]: *** [access.make:578: ../../../../libretro/obj/libretro/src/mame/drivers/acvirus.o] Error 1
make[2]: *** [Makefile:418: access] Error 2
make[2]: Leaving directory '/home/pi/RetroPie-Setup/tmp/build/lr-mame/build/projects/retro/mame/gmake-linux'
make[1]: *** [makefile:1342: linux] Error 2
make[1]: Leaving directory '/home/pi/RetroPie-Setup/tmp/build/lr-mame'
make: *** [Makefile.libretro:242: build] Error 2
```

thats the error i get on a pi4 32bit bullseye

**Comment by chris-est** [comment]
I am getting this error: `src/lib/netlist/plib/ppmf.h:170:17: error: ‘ptrdiff_t’ does not name a type`

Turns out an #include is missing: https://github.com/mamedev/mame/blob/b1a3c44e47864c441ac534b9a0f5855a6a754fa9/src/lib/netlist/plib/ppmf.h#L84
This has been fixed upstream and should be resolved once this repo pulls in the newest upstream commits

**Comment by kwyxz** [comment]
My pull request #316 allows the build, if you don't want to wait for the fix to be merged from upstream.

**Comment by sonninnos** [comment]
No reason to keep this issue still open, or is there?
