### ISSUE TITLE
(MAME current core 0.251) dipswitch menu missing

### ISSUE THREAD

**Issue by ghost** [libretro/mame#350]
Description

I open the MAME menu (TAB key on keyboard) by pushing select + X button but the dipswitch menu is missing.
All other options in the MAME menu are there.

Expected behavior

The dipswitch menu should be shown

Actual behavior

The dipswitch menu is not shown but it should be shown as in standalone MAME version

Steps to reproduce the bug

    Load MAME current core
    Load a MAME game
    Press select + X button to open MAME menu
    See there is no dipswitch menu

Version/Commit

RetroArch 1.15.0
Git version 1581ece

    RetroArch: [version/commit]

Environment information

    OS: Android v12.0

**Comment by riggles1** [comment]
dip switches work perfectly in the 251 (current core), what game are you testing?

https://i.imgur.com/d7afZaS.png

**Comment by ghost** [comment]
I'm testing "asterix.zip" but also in all other MAME games I test, no dipswitch menu appears at all.
Where is the dipswitch menu located? I can't find it. See below for the things I have in the menu.

ps: also in normal MAME the dipswitch menu is gone! Can you please help?

![afbeelding](https://user-images.githubusercontent.com/131728750/234347689-12d38bec-1f84-4e0d-bcc3-60c3de2faa2a.png)

**Comment by riggles1** [comment]
Updated the picture, Asterix isn't a game with dipswitches, it had a service menu (default key is F2 to access it).
Zero Hour is the game in the picture, the majority of games won't have dipswitches, it was more common in old games.

I'm using Windows, I use RA MAME for CRT (CRTSwitchres) output to a Japanese arcade machine (hence my different looking menu font and look I'm using for CRT visibility). So this core gets quite a lot of use from me.

Please don't forget to close the issue btw, feel free to ask me anything MAME related.

**Comment by ghost** [comment]
Thanks a lot!!!!

I now have another problem: how to press F2 on an android tablet in retroarch?
Because the keyboard doesn't show on my tablet and I have no wireless keyboard...

TAB key =  Select + X button, but what is F2 key?

**Comment by riggles1** [comment]
No problemo! You can remap keys in the "mame tab menu">input settings>input assignments (other controls)>service (you can press multiple buttons at once here to have a combo if you want, a dedicated button or set more than one button to do the same thing)
that's just to change the general across all games input default for this. DEL is the default key for setting "none", hit DEL again and it sets back to the default F2.

Some service menus in certain games require multiple service menu buttons. Asterix has a Service 1 key as well (that doesn't seem to be used for this particular game as normal controls navigate the service menu, but for some games they have separate service keys for navigating the service menu).

For individual game keys it's "input assignments (this system) instead, and it'll read whatever key you set for service mode there for that system.

Just additional info unrelated to this:

Since you're on Android, keep in mind that arcade games work at different refreshrates, not always 60Hz. So if some games are stuttery or appear running too fast (in RA you can set audio>synchronization/maximum timing skew, and increase it to something like 17% (how much games are allowed to speed adjust) to allow the games to play sped up to 60Hz instead of stutter). I don't recommend speeding up games that are 55-56Hz however, as the higher pitch music and faster gameplay can be a bit much.

In order to play at native speeds and Hz you'll need either a CRT (CRTEmudriver for CRTSwitchres) or a modern display with Freesync/Gsync.

Asterix is 60Hz though, you can check what Hz games are supposed to run at in the tab menu>system information, it'll say native resolution and refreshrate the game was made for.
