### ISSUE TITLE
Mame runs at 50-55% speed on all games after May 22nd update

### ISSUE THREAD

**Issue by Missingno255** [libretro/mame#371]
lr-mame runs at 55% speed, without frame skipping, on all games on Raspberry Pi 4. Last week, it ran at 100% full speed with no problems. Even games like Donkey Kong, run agonizingly slow now. Frame skipping only boosts it to 60%. I tried deleting retroarch configs to fix it, but that didn't work.

**Comment by MistyDreams** [comment]
Yea the updates effected the alt renderer(mame default but its was always partially broke the way the libretro res was hacked in). 

I really dont know why libretro didnt use the switch res that does this already without messing about with the main rendering engine. Anyway go to your quick menu options choose rotation mode as libretro and choose alternate renderer off. You should be go you will need to restart after changing  the, settings.

**Comment by Missingno255** [comment]
> Yea the updates effected the alt renderer(mame default but its was always partially broke the way the libretro res was hacked in).
> 
> I really dont know why libretro didnt use the switch res that does this already without messing about with the main rendering engine. Anyway go to your quick menu options choose rotation mode as libretro and choose alternate renderer off. You should be go you will need to restart after changing the, settings.

Didn't work. Rotation was already set to libretro and alternate renderer set to off.

**Comment by MistyDreams** [comment]
backup the config settings you have for mame and the delete the original settings file. start mame so it creates a new one. Aslo make sure there is no overrides.

**Comment by Missingno255** [comment]
> backup the config settings you have for mame and the delete the original settings file. start mame so it creates a new one. Aslo make sure there is no overrides.

Still didn't work. Deleted the configs (except game configs) and overrides are off.

**Comment by FollyMaddy** [comment]
Same issue over here on Debian 11 Bullseye 64 bit VM on Macbook pro (2.5Ghz I7)
(This setup should be beefy enough )
(On my Ubuntu 22.04 64 bit VM the version from 2 April at commit cd5f7d077cdab2eac09faf642ddd121d80f3ad1b is fine on the same computer)

Reinstalled newest RetroArch from source ( and SDL2 not sure if it's needed but did that anyway )

Tested and did not work :
- alternate renderer set to off
- rotation modes on libretro

Tested other combinations of above and did not work

Other suggestions ?

**Comment by sonninnos** [comment]
No difference with my machine. Was the previous commit fine?

**Comment by LibretroAdmin** [comment]
Can the OP do a bisect?

**Comment by FollyMaddy** [comment]
@sonninnos 

I tested the latest (30 may at commit 0f033862d86ccd81aa67308063b92cac0f1d0db1) again on my Ubuntu 22.04 VM 64 bits and it was ok !

The Debian 11 64 bit VM has one from one day ago using (23 May at commit 0cabe940eca02f22397f66a6c20923af04dccd3d which runs on +/- 50% with audio hick-ups.

If I can then I will try the newer version tomorrow on the Debian 11 to see if that still has the issue.


Update :

Ok, I tested the latest (30 may at commit 0f033862d86ccd81aa67308063b92cac0f1d0db1) again on my  Debian 11 64 bit (x86_64) VM and it still had the same issue. (runs on +/- 50% with audio hick-ups)

I tested the latest (30 may at commit 0f033862d86ccd81aa67308063b92cac0f1d0db1) again on my  Debian 11 64 bit (aarch64) VM (a clean OS !) and it seems to run fine but has dips to 80% and it doesn't look smooth and has some audio crackles sometimes.
So it seems it has the same issue but not so noticeable because of the better specs of the computer.
(VM runs on Apple M1)

**Comment by LibretroAdmin** [comment]
As earlier requested, please get us an EXACT bisect and an exact commit that you conclude is the culprit of the speed reduction.  Anything else is not useful.

**Comment by FollyMaddy** [comment]
I will move back to a commit before 22 may and try to find the commit where the issue appears.

Please be patient, I haven't got much time to test so it will probably take more than a few days !

Btw. I am not the OP, I am here to help

**Comment by Missingno255** [comment]
I am the OP. I'm not familiar with what a "bisect" is as I'm not experienced with github, and I use this account, mainly to report problems. So forgive me if I don't know exactly how to do things on here, as this is a learning experience for me.

**Comment by Missingno255** [comment]
I'm the OP. I'm not familiar with what a bisect is or with Github in general (I don't use this account very often, mainly for reporting problems) and I apologize if I cannot get what is needed.

**Comment by LibretroAdmin** [comment]
> I'm the OP. I'm not familiar with what a bisect is or with Github in general (I don't use this account very often, mainly for reporting problems) and I apologize if I cannot get what is needed.

Find the commit that caused what you stated in the OP (the speed reduction). That's what a bisect means. Identify the culprit.

**Comment by sonninnos** [comment]
Please test if the recent change makes any diffence.

**Comment by FollyMaddy** [comment]
I tested the latest now on my Debian 11 64 bit (x86_64) VM :
- 5 June at commit https://github.com/libretro/mame/commit/5e04369f1154f5458431fd9e01b7c70cf14ff932

Great, the speed is good again just like before.
There is still a little ticking issue in the audio but that issue was there before in VMware.
Could be a VMware issue, really not sure.

I tested it also on a AMD Phenom II X6 PC Debian 11 64 bit (x86_64)
Everything seems to be ok.
Speed is good no audio ticking.

Tried it also on my Debian 11 64 bit (aarch64) VM.
Here these issues still persist ( although good enough to use and play with ) :
- speed dips sometimes to 80% 
- it doesn't look perfectly smooth 
- ticking and audio crackles sometimes.

My guess is that the "speed / smoothness issues" persists probably due to the fact that VMware on Apple M1 has no open-vm-tools yet to enable 3d Acceleration and other stuff properly.

It probably will work again for the RPI4 too.

Can the OP test it again ?

**Comment by Missingno255** [comment]
> I tested the latest now on my Debian 11 64 bit (x86_64) VM :
> 
> * 5 June at commit [5e04369](https://github.com/libretro/mame/commit/5e04369f1154f5458431fd9e01b7c70cf14ff932)
> 
> Great, the speed is good again just like before. There is still a little ticking issue in the audio but that issue was there before in VMware. Could be a VMware issue, really not sure.
> 
> I tested it also on a AMD Phenom II X6 PC Debian 11 64 bit (x86_64) Everything seems to be ok. Speed is good no audio ticking.
> 
> Tried it also on my Debian 11 64 bit (aarch64) VM. Here these issues still persist ( although good enough to use and play with ) :
> 
> * speed dips sometimes to 80%
> * it doesn't look perfectly smooth
> * ticking and audio crackles sometimes.
> 
> My guess is that the "speed / smoothness issues" persists probably due to the fact that VMware on Apple M1 has no open-vm-tools yet to enable 3d Acceleration and other stuff properly.
> 
> It probably will work again for the RPI4 too.
> 
> Can the OP test it again ?

I can confirm that it is working again on Raspberry Pi 4. I checked the speed at ~98-101%. Music seemed good on my end at least.

**Comment by FollyMaddy** [comment]
@Missingno255 
Ok, good to know.
Thanks for testing it out.
Seems you can close the issue now.

@sonninnos 
Thanks for fixing it.

**Comment by sonninnos** [comment]
Great, thanks for confirming.
