### ISSUE TITLE
[Windows] Mame.ini samplepath not taken into account [$15]

### ISSUE THREAD

**Issue by obenguerah** [libretro/mame#40]
Paths parameters are not taken into account when updated in system/mame/ini/mame.ini file

Workaround would be to allow this options to sit into the core_options.

Idea was to have samples sitting along with Roms, and not into the System (ideally without entering a absolute path. ie: mame_path_samples = _CONTENT_\samples )

Thanks

**Comment by crocket** [comment]
system/mame/ini/mame.ini is not read by mame-libretro.

**Comment by RetroUp** [comment]
Sample Path from ini's is never read because it is hard coded to the Retro Arch system dir.

How would you want this solved
1. Remove the hard code. Set the default value to a likely guess of "./system/mame".
2. Leave the hard code but add an option in retroarch-core-options to change the path. The path in ini files would still never be read.
3. Leave the hard code but add an option in retroarch-core-options to disable it. The path in ini files would be read.
4. Enable the hard code only if sample path in ini is set to "default" otherwise read the path from ini. Could be a problem if you enable write config, and then change the system dir in RA but leave the old ini files. The old RA system path  would be saved to ini but wouldn't update to the new path. This could cause confusion.


This same problem applies to the paths for "states", "snaps", "diff", "artwork", "cheat", "ini", and "hash".

**Comment by RetroUp** [comment]
Bump, I'd like some feedback before doing this. I can see pros and cons for each method. If I don't hear back in a week or so I'll just pick a method and do it.

**Comment by r-type** [comment]
to me , third option seem fine.

**Comment by RetroUp** [comment]
Complete -> https://github.com/libretro/mame/commit/9f9e6b6c9bde4d50c72e9a5c80496a1fec6b8aa9

I think this can be marked closed.

**Comment by NelsonRosenberg** [comment]
@RetroUp I am having a little trouble with this. No matter what option I have in the "MAME INI Paths" variable, the mame.ini rompath is never read. It always defaults to the selected rom path.

**Comment by obenguerah** [comment]
@tcamargo  .... Issue still here, not sure why this issue was closed

**Comment by tcamargo** [comment]
@obenguerah because of https://github.com/libretro/mame/issues/40#issuecomment-421162374

**Comment by NelsonRosenberg** [comment]
So one interesting thing is that for me the mame.ini file is not read from `<retroarch_path>/system/mame/ini/mame.ini` when I set "MAME INI Paths" to true. It is actually read from the same folder where retroarch.exe lies. I could easily test that by modifying my samples folder and checking the result in the Mame UI after loading a game that requires samples (like zaxxon)

- "MAME INI Paths" = false.  => Paths are set with retroarch default values, which for samples is `<retroarch_path>/system/mame/samples`. In my case `C:/Retroarch/system/mame/samples`
- "MAME INI Paths" = true and mame.ini in `<retroarch_path>/system/mame/ini` => sample path is set with some kind of mame defaults, `system/mame/samples`, without the `C:/Retroarch`.
- "MAME INI Paths" = true and mame.ini in same folder as retroarch.exe => samples path is correctly set to any folder I set in the mame.ini

But even with being able to set the mame.ini paths of all the folder, it still won't overwrite the one for the rompath, which means this bug is still happening.

There is also another option called "Read configuration" which I am not sure what it does?

Hope that helps. Thank you

**Comment by beemandev** [comment]
I was trying to track down why hiscores saving but not reloading with mame core and I  noticed that the "Change Default MAME Paths"  commit above has prepended all mame paths with "system/mame/" but in Set_Path_Option() function it calculates path using :-
snprintf(tmp_dir, sizeof(tmp_dir), "%s%c%s%c%s", retro_system_directory, slash, core, slash, dir_name[i]);
so prepends the path with "system\mame\" again => ..\retrorarch\system\mame\system\mame\roms

I was just browsing the github on a web browser so haven't looked in depth and maybe I misunderstood something, but...

**Comment by sonninnos** [comment]
Not happening here though. It simply sets those under `system/mame/`.

**Comment by beemandev** [comment]
OK, Maybe I misunderstood the settings in emuopts.cpp that appear to do this
`{ OPTION_HOMEPATH,                                   "system/mame",         OPTION_STRING,     "path to home directory (read/write) location" },
	{ OPTION_MEDIAPATH ";rp;biospath;bp",                "content/mame",      OPTION_STRING,     "path to ROMsets and hard disk images" },
	{ OPTION_HASHPATH ";hash_directory;hash",            "system/mame/hash",      OPTION_STRING,     "path to hash files" },
	{ OPTION_SAMPLEPATH ";sp",                           "system/mame/samples",   OPTION_STRING,     "path to samplesets" },
	{ OPTION_ARTPATH,                                    "system/mame/artwork",   OPTION_STRING,     "path to artwork files" },
	{ OPTION_CTRLRPATH,                                  "system/mame/ctrlr",     OPTION_STRING,     "path to controller definitions" },
	{ OPTION_INIPATH,                                    "system/mame/ini;system/mame/ini/presets",     OPTION_STRING,     "path to ini files" }

**Comment by sonninnos** [comment]
I'll close this since samples work just fine here when the paths are manually defined in mame.ini, by enabling both "Read Configuration" and "MAME INI Paths".
