### ISSUE TITLE
[Regression/Windows 11x64] Taito G-NET games crash at startup since core 0.256

### ISSUE THREAD

**Issue by Immersion95** [libretro/mame#416]
Those games crash at startup and only display the color bands before exiting RA.

Example : Zooo & Chaos Heat

It was working perfectly with 0.251, I couldn't find a 0.255 core to test.

Please remember that those games are CHD only, you need the coh3002t.zip bios and an empty zip (or whatever inside) named after the chd.
zooo.chd + coh3002t.zip + zooo.zip --->Launch zooo.zip with RA with Mame core.

**Comment by msheehan79** [comment]
Can confirm same issue here on Windows 10 x64 - I had compiled a copy of 0.255 locally in early June and that build works fine, but the latest buildbot version downloaded today crashes for me as well with the same ROMs (I did not see any changes to the G-NET romset with 0.256 so am assuming that isnt the issue here).

Here is the commit info I see in RA for the 0.255 core that does work.

![image](https://github.com/libretro/mame/assets/1565622/1f9d1252-c324-4f93-b89f-e8f145311db7)

**Comment by Immersion95** [comment]
Here is a log, sorry I forgot.
[retroarch.log](https://github.com/libretro/mame/files/12206647/retroarch.log)

**Comment by Immersion95** [comment]
Sorry, this bug comes from upstream. I forgot to try, the latest 0.257 solve it.
