### ISSUE TITLE
keyboard issue

### ISSUE THREAD

**Issue by grant2258** [libretro/mame#418]
The enter key does not work on the osd menu unless you use game focus mode

**Comment by sonninnos** [comment]
Enter key is RetroPad Start by default, and after changing to keyboard events there are no more duplicate presses, but only frontend action if not empty. So you'd either need to map Start as MAME UI menu ok button, or unbind Enter as Start ,or use Game Focus. Maybe we could add Start to act as menu ok by default since it isn't doing anything.

**Comment by grant2258** [comment]
every single retropad map is a duplicate process. Like I said the enter key works fine in game focus mode without changing any settings. I dont understand why we are disabling keys makes using the boot to mame awkward. Ill just use game focus mode I test via the keyboard. There is no need to drop the keypress that and the retropad is sent at the same time. Ill just close this since its intended behavior. I would stick to game focus as some users use keyboard encoders for there barcade setup. There is no easy way round this apart from leaving an option to to set the input type as retropad,keyboard,or both at the same time like 2003-plus does. An api option to not pass the keyboard retropad input on for cores that need full keyboard access would be an ideal solution. Hotkeys are easily dealt with using a modifier.
