### ISSUE TITLE
1 frame of input lag in the RA core

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/mame#53]
I was testing a particular game on RA vs stand-alone MAME and noticed there's always 1 additional frame of input lag in RA.

Testing is putting the game on pause (P), keeping an action button pushed down, going to next frame (K in RA, left_shift+P in MAME) until the action has an effect on screen.
The result is always 1 more frame in RA.

Is there something that could be changed, like the place where the input is polled in the port, to fix that?

Mame 0.193 / core 0.193, RA 1.7, win7 x64.

**Comment by Tatsuya79** [comment]
The polling seems to be happening here atm:
https://github.com/libretro/mame/blob/master/src/osd/libretro/video.cpp#L125

**Comment by ghost** [comment]
maybe try to poll and update input before video_cb(), my cpu takes 2hrs for mame to build so sadly cant test :( (mame doesnt seem to use ccache for some reasons....)

**Comment by vadosnaprimer** [comment]
@retro-wertz you don't have to build the whole thing for a basic test.
`make SUBTARGET=pacman SOURCES=src/mame/drivers/pacman.cpp REGENIE=1 IGNORE_GIT=1` only builds pacman and is decently fast.

**Comment by ghost** [comment]
nah even with that, it still takes awhile long to compile and warnings are considered errors so it fails.
Compiling src/osd/libretro/retromain.cpp...
In file included from ../../../../../src/osd/libretro/retromain.cpp:24:0:
../../../../../src/osd/libretro/osdretro.h:26:6: error: "USE_XINPUT" is not defined, evaluates to 0 [-Werror=undef]
 #if (USE_XINPUT)
      ^~~~~~~~~~
../../../../../src/osd/libretro/retromain.cpp:80:6: error: "USE_XINPUT" is not defined, evaluates to 0 [-Werror=undef]
 #if (USE_XINPUT)
      ^~~~~~~~~~
cc1plus: all warnings being treated as errors

**Comment by r-type** [comment]
use NOWERROR=1
https://github.com/libretro/mame/tree/master/src/osd/libretro/libretro-internal

**Comment by ghost** [comment]
thanks never knew a readme existed there. havent find something that allows
using ccache though....

(waiting compile to finish....)

**Comment by Tatsuya79** [comment]
Something strange, but writing it here just in case:

A game like Viewpoint (Neo-Geo) which has 2 frames of "internal input-lag" in Mame, has 3 in RA-Mame and 3 in RA-FBA.
The King Of Fighters '98 (Neo-Geo) has 6 frames in Mame, 7 in RA-Mame, 6 in RA-FBA.
Guwange (cave) has 3 frames in Mame, 4 in RA-Mame, 4 in RA-FBA.

...but that's probably something to investigate with FBA.

**Comment by ghost** [comment]
is it possible if you can compare with mame2010 or something else?

**Comment by Tatsuya79** [comment]
Similar results in mame2010 & mame2014 (couldn't test 2016 as P is hard-coded and conflicts with RA):
Viewpoint 4 frames (+2 vs stand-alone Mame 0.193)
KOF98 8 frames (+2)
Guwange 5 frames (+2)

So it seems to be worse.

**Comment by Tatsuya79** [comment]
Older cores (2010/2014/2016) should be on the same level as that one now (1 frame slower than stand-alone instead of 2) with recent commits.
Haven't tried 2000/2003 though.

But we could still recover that extra frame if the polling happened earlier...

**Comment by Tatsuya79** [comment]
As I can compile this core fine now I tried to move the polling around in video.cpp or libretro.cpp but it doesn't help.
I wanted to test moving the polling methods to various mame files but I don't really understand all that structure stuff and how to call the machines.

If someone got an idea with the precise code and declarations needed I can then compile and test the input lag.

**Comment by r-type** [comment]
BTW the way it is done is how the polling was done in other osd , 
in windows_osd_interface::update(bool skip_redraw)
https://github.com/libretro/mame/blob/master/src/osd/windows/video.cpp#L85
I think you should not move this or call this elsewhere.

**Comment by r-type** [comment]
maybe you can test to change the input_poll_type_behavior in RA retroarch.cfg to see if it change anything

**Comment by Tatsuya79** [comment]
Nope, RA poll setting does not help here, always too late into the next frame... :/

**Comment by Ryunam** [comment]
Thank you for opening this issue! Just a few days ago I was dabbling with a stand-alone build of Mame, GroovyMAME specifically, and I definitely noticed the 1-frame input delay in the RA core.
This is especially apparent when pausing emulation and advancing frame by frame: the RA cores of both MAME and Final Burn consistently exhibit 1 more frame of input delay.

SNES cores were affected by the same issues, especially bsnes cores, before @Brunnis applied his fix. I think it could be remedied by performing a similar modification of the code and this would make the RA core quite as responsive as GroovyMAME itself (with the added benefit of an easier shader management), but I am nowhere near competent enough to attempt it personally.

**Comment by Ryunam** [comment]
I have tried moving around input_poll_cb() in https://github.com/libretro/mame/blob/master/src/osd/libretro/video.cpp#L125 to several locations, but it doesn't seem to produce any discernible effect. 

I believe that the culprit would have to be found in the libretro folder, since we are talking about an additional frame of input lag that is inherent to the libretro implementation.

Has anyone had any luck with this so far?

**Comment by Tatsuya79** [comment]
I've tried a lot of things, moving the polling to retro_run to populate an external table that goes into input_retro and then change the order of different calls in video.cpp... but nothing better.

I wonder if [that downcast thing](https://github.com/libretro/mame/blob/master/src/osd/libretro/video.cpp#L117) is supposed to be the way to update the polling into the virtual machine before the screen drawing.

**Comment by Ryunam** [comment]
Yeah, I’ve thought the same, it definitely caught my eye when trying to mess with the code and trying to anticipate the polling.
Something I was wondering though: maybe the position of the polling is actually correct and what is happening is a conflict between RA’s V-Sync and Mame’s own internal V-Sync settings, adding exactly 1 more frame to the process. It is just an idea that’s still not backed-up by anything, but I am wondering if the culprit is somewhere else than in the input polling code.

**Comment by r-type** [comment]
@Tatsuya79  can you try on old alt mame2010 (libco) to see if input lag is same ?
https://ufile.io/qrtfd

**Comment by Tatsuya79** [comment]
I tried to build from https://github.com/libretro/mame2010-libretro/commit/5576b2a0678504ed13487075cfcb84fd26b252e5 or https://github.com/libretro/mame2010-libretro/commit/d12bde8989984a5dcc7aa243f37f922911d3f24b but I get a core that gives me a black screen and spams "Running a dead emulator" in the logging window.

I'm on win7 x64 with msys2/mingw64 gcc 6.3, I compiled with make -j4
also tried 
make "VRENDER=soft" "PTR64=1" -j4
but same result.

...seeing the "buildtools" note now, gonna try that.

...nope same result. :/

Found a backup I had from March 2015, it closes on launch, no error message... this looks complicated.

**Comment by r-type** [comment]
@Tatsuya79 the one i link above works for me with windows 10 x64 , and it's a libco release.
but maybe it don't work in win7. it will be interesting to know if lags happen also with libco

**Comment by Tatsuya79** [comment]
Thanks your core is working here.
Same lag compared to current mame cores (2010, 2014, 2016 and most recent).

Using pause/next frame from RA hotkeys gives me 4 frames on my reference test.
If I use pause/next frame from Mame hotkeys (in RA or in stand-alone) it gives me 3 frames.

The FBA core is doing things differently as 2 frames reaction will become 3, but longer ones will be like stand-alone Mame.
Here with Mame cores it's always +1, even on a reaction test of 6 frames, it will become 7.

**Comment by r-type** [comment]
> If I use pause/next frame from Mame hotkeys (in RA or in stand-alone) it gives me 3 frames.
so the lag is the same if you use mame key (for RA and stand-alone) ? but not if you use RA pause key ?
if so it's RA related ?

**Comment by Tatsuya79** [comment]
I'm still wondering where it happens.

When we use the Mame pause hotkey in the RA core, it's just the emulated machine that is paused, Mame still runs and you can bring up the GUI.

So I wondered if the same happened in stand-alone Mame: is it really reacting in 2 frames on the screen?
So I recorded a video of kof98 menu in stand-alone, put Mame on pause on, pushed a key down, unpaused it.
Then watching the video I can count the frames it takes as the menu background is scrolling: it's really 2 frames before selecting a character.

The FBA core also takes 2 frames to select a character in RA.
(I wanted to test FBA stand-alone too but it has no frame step advance feature.)

So, in the end there's really a lost frame in response time in every Mame RA cores.
But is it really the polling or the way the Mame GUI part could add a delay? (as every past core seems to have that lost frame despite different methods)

**Comment by Tatsuya79** [comment]
I did some video recording of FBA stand-alone and it reacts the same way as the FBA RA core:
KOF98 is as fast as Mame stand-alone but other games on the same neogeo driver such as Last Resort or Viewpoint react in 3 frames while Mame stand-alone reacts in 2...

So FBA is ported as intended, its issues are from upstream.

Also confirmed that in Viewpoint the ship can fire in 2 frames in Mame Stand-alone (3 in RA).

**Comment by vadosnaprimer** [comment]
RA doesn't send inputs to the game with mame, it sends it to its OSD ("OS Dependent" layer that talks to the machine). And OSD doesn't seem to send those inputs the same moment it gets them, but only with some delay, since mame is based on timers and stuff. Its UI commands get polled pretty frequently while machine is paused, but I'd assume machine lag comes from the process of this translation: RA -> OSD -> machine. RA doesn't send it game inputs, it's sending it real world key presses, that's the reason I think.

**Comment by Tatsuya79** [comment]
Perhaps we're missing the trigger to [start the device event here](https://github.com/libretro/mame/blob/master/src/osd/modules/input/input_retro.cpp#L959)? (and so it would start by default at the end of the frame = too late)

Other input modules seem to do something here, like [x11 ](https://github.com/libretro/mame/blob/master/src/osd/modules/input/input_x11.cpp#L522)and [raw ](https://github.com/libretro/mame/blob/master/src/osd/modules/input/input_rawinput.cpp#L633)as example.
Or this could just be OS specific and the "event trigger" could be done somewhere else...

**Comment by Ryunam** [comment]
Is the additional frame of input lag still present after the latest (0.194) update?
EDIT: Just tested it, it is still lagging behind by 1 frame.

**Comment by Ryunam** [comment]
I have just contributed a $30 bounty towards this issue, in an effort to hopefully reignite interest on the matter. See Bountysource thread here: https://www.bountysource.com/issues/53180296-1-frame-of-input-lag-in-the-ra-core

Hopefully this provides further incentive to look into this discrepancy and shave off this additional frame of input latency, bringing all MAME RA cores up to the same standards as standalone.

EDIT: Added $10 more.

**Comment by Zarkovian** [comment]
I'm also noticing the 1 frame of additional lag in RA MAME and can confirm it through use of the frame stepping method (pause+k).

I accidentally stumbled upon an issue that may help uncover what's going on.

It's the game **Pengo**, if you run it with RA setting "**Poll Type Behaviour**" set to "**Early**" AND **Frame Delay is 3 or higher**, start the game, then it will complete each Act by itself instantaneously and indefinitely.  So it loads a level and immediately you get the tune tadadadatata (success) and it moves to the next Act / Level, only to repeat the process. Within 30 seconds you're at Act 10... The game reports for each level that it took about 1:40m to complete, so there's something really strange going on.

Tested both in latest 0.198 and 0.199 RA MAME. 

Note that this does NOT happen when "Poll Type Behaviour" is set to "Normal" or "Late" or Frame Delay at 0, in that case it will run normal, just as regular MAME. Only happens when Poll Type Behaviour is set to "Early" and a Frame Delay of 3 or higher.

Since this is such an obscure "bug", related to input polling, that maybe it is of help uncovering the 1 frame of additional lag of RA MAME versus regular MAME.


EDIT: I tried to record a movie of it, but when recording is enabled the issue does not occur. I guess this may be because with recording enabled the Frame Delay gets disabled?

**Comment by RetroUp** [comment]
Problem solved in a round about way. Tested on Win64 only.

I spent a couple days looking into this. I tried multiple versions of mame. With and without libco. I tried FBA. I added GroovyMame to RA-MAME. I edited the polling every way I could think of. I tried adding Brunis's fix. I searched the internet for mame lag hacks. No mater what there was always a +1 frame lag.

Then finally after I had pretty much given up I tried using MAME's step pause instead of RA's. And tada, no lag. There never was a lag. Tried in MAME 0.181 and no lag there either.

To duplicate, enter MAME's tab menu and assign Pause - Single Step to a key unused by RA. Then use that key to test the lag instead of K.

**Comment by krispya** [comment]
I did some testing on this myself using Metal Slug 3 and verified the 1 frame of input lag on Windows 64-bit and Android 32-bit systems.

**Comment by krispya** [comment]
Per Grant's request I did an input test on MAME with Metal Slug 3 in RA. First I used RA's pause + frame step which gave me 3-4 frames. Then I used MAME OSD's pause + frame step inside of RA, which gave me 2-3 frames, the same as stand alone. The difference may just be due to how frame stepping works. Can someone do a high speed camera test?

**Comment by Tatsuya79** [comment]
I'm wondering if it's because we use 1 frame for the game then 1 additional frame to display the GUI?

**Comment by Tatsuya79** [comment]
I recorded with OBS on my win7 pc, RA vs MAME both windowed, exact sync/hard sync off in RA, both throttled to be at the same speed, vsync on/gsync off, no shader.

[sonic latency.zip](https://github.com/libretro/mame/files/3680711/sonic.latency.zip)

They react at the same timing most of the time, MAME is faster once at 3s then RA is faster twice at 9s.
So we can assume MAME is omitting a frame with its own "next frame step" method that RA shows as it's running the whole MAME with its interface inside its own execution timing.

RA and Mame should then have the same response, faster in RA if you lower it with advanced options to shorten the rendering such as hard sync or frame delay .

edit: I tried in a bit more length.
Jumped 50 times with Sonic: 19 weren't synced between both emus.
Mame was faster 12 times, RA 7 times.

Not sure if this method is really good, who knows how windows or the GPU drivers act and give priority to each emu.
Fullscreen and a fast video camera would be better.

**Comment by Tatsuya79** [comment]
I had my screen at 120hz on my previous test, I decided to try again at 60hz to be sure I'm in sync with the 60hz recording.
RA reacted 1 frame earlier than MAME 22 out of 25 times so I guess we're good.

**Comment by Ryunam** [comment]
That is interesting, thanks a lot for performing these tests. The evidence collected so far does seem to be rather conclusive, so I'm wondering about what to do with the existing €140 bounty.

I cannot speak for @Bubs who invested $100 on this, but if that's possible I would like my $40 to be used as a contribution for the beetle-psx dynarec development.

**Comment by Tatsuya79** [comment]
And the extra frame was in MAME upstream already:
https://github.com/mamedev/mame/pull/5901

**Comment by obenguerah** [comment]
I'm bubs (changed login).

Is it still relevant to keep this issue open? anyone has tested mame core after this one : https://github.com/mamedev/mame/pull/5901

Otherwise, if I can move my $100 to another topic, I would love to sponsor RunAhead on MAME Core if it makes sense..

**Comment by Tatsuya79** [comment]
This commit doesn't seem to change anything for RA.
I still don't have anything to record the screen directly though, just testing frame step.

**Comment by tcamargo** [comment]
I have the impression the mentioned commit is only valid if vsync is off. So, good results only with VRR monitors.

”However, if throttling is disabled with v-sync on (-nothrottle -waitvsync), like it's usually done to achieve smooth scrolling, there will be no benefit, since inputs will be polled immediately after rendering. Latency figures with vsync-on are terrible nevertheless.“

I don’t have the equipment to test. @Tatsuya79 what settings did you use in your tests?

**Comment by Tatsuya79** [comment]
Gsync, vsync on in RA, exact sync on, throttle on in MAME.
The way it needs to be if you want the games to run at their real speed with gsync active.

**Comment by tcamargo** [comment]
Try with v-sync off.

**Comment by Tatsuya79** [comment]
It makes no difference for the "next frame" hotkey.

**Comment by obenguerah** [comment]
> I had my screen at 120hz on my previous test, I decided to try again at 60hz to be sure I'm in sync with the 60hz recording.
> RA reacted 1 frame earlier than MAME 22 out of 25 times so I guess we're good.

@Tatsuya79, could you share your RetroArch latencys configuration (including poll setting)? I'm starting to measure latency using a high speed camera (Iphone high speed camera + "Is It snappy?" app) and trying to put in place the right bench test...

T

**Comment by Tatsuya79** [comment]
Poll setting doesn't seem to make any difference, I keep it on "late" which is theoretically the best/shortest time before vblank.
Then if you're comparing with stand-alone MAME it depends of its settings too
(recently it supposedly got quicker with lowlatency 1 alongside waitvsync/syncrefresh 0 for vrr screens).

On the RA side, if using gl/glcore driver you want hard sync at 0 frame to be the quickest.
With vulkan "max swapchain image" at 2 (1 is usually not accepted by drivers I was told) should give you the same speed without the extra cost on the cpu that you have with gl.

I wouldn't bother with "frame delay" as we know it's really tied to your computer and the game running, for smaller gains in the end.

With a g-sync screen I have "Enable throttle" on in MAME core options, 
also "Sync to exact content framerate" in RA settings>frame throttle, 
and in settings>video>output main Vsync is enabled, vertical refresh rate on my monitor max (120hz).

**Comment by tcamargo** [comment]
So, what is the final verdict?

**Comment by HappehLemons** [comment]
Does this issue still exist?

**Comment by Tatsuya79** [comment]
Yes, and there's lag.
I did some high framerate camera recording since I got a new phone, my results (240fps frames, gsync):

windowed:

MAME
6 10 10 10 7 12 10 10 10
>9.4 = 39ms

RA
13 13 13 11 13 10 12 11 11 10
>11.7 = 49ms

fullscreen:

MAME
7 7 7 8 10 7 4 8 9 5 10 8
>7.5 = 31ms

gl
10 11 11 11 9 8 10 10 10 9
>9.9 = 41ms

vulkan
10 10 11 10 11 11 10 8 10 8
>9.9 = 41ms

**Comment by Ryunam** [comment]
Wow, this sure is a long-standing problem… My own posts here date back to 2018.

I’m wondering whether this is a matter of the MAME core somehow already applying its own V-Sync internally and then RA doubling down on it, creating this additional frame of latency because of a “double V-Sync” thing. But this is pure speculation on my part, no idea whether that’s even possible.

**Comment by Ryunam** [comment]
Thanks a lot, it's amazing to see this finally fixed!
