### ISSUE TITLE
Mouse right and middle button not working

### ISSUE THREAD

**Issue by Aethyrion** [libretro/mame#79]
Mouse right and middle buttons are not working in MAME core (and cannot be assigned in Mame TAB menu), while left button is working properly. Input driver is set to dinput (same issue with sdl2), in-game mouse is enabled in core options (mouse support appears also enabled in MAME advanced options menu).

Everything is working properly in the same version of standalone MAME . Right mouse button is working properly in other cores.

Windows 10 x64
Retroarch 1.7.4
Mame 0.201

**Comment by tcamargo** [comment]
Could you please test a newer build? If problem persist, please reopen this issue.

**Comment by Aethyrion** [comment]
Issue still present in Retroarch 1.8.8 with MAME 0.220. The right mouse button cannot be assigned to any control in the MAME menu.

I'm not sure I have the right to re-open the issue.

**Comment by ToniBC** [comment]
The bug is still present in Retroarch 1.9.1 Nightly and MAME 0.230.

You cannot map the right button, but in MAME Standalone you can.

Something happens that the core does not detect the mouse correctly.

**Comment by ToniBC** [comment]
Nobody looked at the mouse button bug, it is strange, because it does not have to be very complicated, the left one works, but not the others, it has to be something simple to solve. We are in the latest version 0.235, but the error continues.

More than anything because it is almost the only thing that fails and affects all pistol games.

Let's see if anyone remembers this bug.

Thanks.

**Comment by StormedBubbles** [comment]
Hello,

I resolved this issue with the above commit and also enabled multimouse/lightgun support.

**Comment by ToniBC** [comment]
Yes, the mouse seems to work now.
