### ISSUE TITLE
Left Analog Stick is broken.

### ISSUE THREAD

**Issue by PixelCrusader** [libretro/mame#86]
Windows 7 64 bit, AMD Radeon HD 6450, Intel i5-2320 CPU @ 3.00GHz
RetroArch 1.7.5 7c93a0934e - MAME 0.203 (2018 11-09 2:37)

Updated MAME from the base .203 update to check another issue. Now the left analog stick doesn't work properly. Trying to calibrate the controls shows that pressing up is registered as pressing down and vice versa. Everytime the stick is used the character goes towards the left, despite the UI saying that left is left and right is right. Despite trying to clear the cfgs and start from scratch, this is persisting. Other cores, including MAME 2016 are not displaying the issue so I can only imagine it had to do with a recent update.

Using a DualShock 4 wrapped with DS4Windows v1.5.9

**Comment by Awakened0** [comment]
I haven't noticed anything different with analog steering in Outrun or Outrunners using the left stick on my Xbox One controller in Windows. I did have to invert the Y axis in Space Harrier to make up = up and down = down like I had it before though. I had Y Reverse set to on before, now it's off. There are options for that in MAME's UI under Analog Controls. But I don't think you can set that globally, so you probably have to set it for each game.

**Comment by PixelCrusader** [comment]
I experienced the same situation with Spacer Harrier and OutRun as well. Arcade games that cause the Analog Controls option to emerge in the MAME UI look to be still playable, flipped Y axis aside. The biggest problem is with games that don't. Like beat em' ups or Pac-Man or vertical scrolling shooters. You can no longer use the left analog stick to move around because the character spazzes out and mostly goes left. This isn't occurring in standalone MAME .203.

Of course you can just use the D-pad instead, but I felt these problems were significant enough to make a note of.

**Comment by Awakened0** [comment]
Oh, I see. I don't map the analog stick to movement controls for digital movement games. At least not in MAME's UI. I use RetroArch's "Analog to Digital Type" input option set to "Left Stick" under "User 1 Binds" for that, which still works fine. That's an easy, quick way to have digital movement mapped to both the d-pad and left stick. Then I set per game overrides to disable that option for games that do support analog. This method works around the problem since the frontend is handling mapping the stick to d-pad inputs instead of the core.

@Tatsuya79 Added analog trigger support recently, so it's possible that commit is causing wierdness when mapping stick axis's to digital inputs in MAME's UI. Could be changes from upstream too, of course.
