### ISSUE TITLE
Unable to launch a lot of different systems

### ISSUE THREAD

**Issue by Sterophonick** [libretro/mame#97]
This version of MAME is unable to launch MESS systems that don't have a software list. Those systems include, but are not limited to:
The Tiger Electronics handheld games
Game & Watch
Coleco Tabletop
Tamagotchi
Konami Handhelds

Please devise of a way to allow these games to be launched on this version.

**Comment by r-type** [comment]
don't sure to understand what your are saying

```
retroarch  -L mame_libretro.so   gnw_mario.zip
```
![gnw_mario](https://user-images.githubusercontent.com/3614417/55190612-74573400-51a0-11e9-9c14-4b6f77a64dbe.png)

**Comment by meowthed** [comment]
trying to launch these games using retroarch's frontend crashes retroarch for some reason, I would extend the XaviX/Sunplus games here too.

**Comment by r-type** [comment]
https://github.com/libretro/mame/issues/98#issuecomment-478622397

But it appear you have to have core option "mame_boot_from_cli" enable , option that i always had enabled so i didn"t notice the failure when disabled!

**Comment by r-type** [comment]
the problem is in  execute_game(char* path) func
that don't handle properly thoose systems. (if the system is not an arcade and dont have a software list).
it act like adding such options
 -rompath path
 path/gnw_mario.zip
 gnw_mario

and then end up with something like 
```
Error: unknown option: gnw_mario
```
instead of doing 

 -rompath path
 gnw_mario

BTW the func static int execute_game_cmd(char* path)
handle thoose systems correctly that why they boot fine using core option "mame_boot_from_cli" enable.

so temporaly fix is to enable "mame_boot_from_cli" core option.
